### ISSUE TITLE
Allow TUOM to carry either conversion from/to expressions OR a single conversion factor

### ISSUE THREAD

**Issue by djjd47130** [djjd47130/JD-UOM#65]
# Goal

To reduce the overhead on unnecessary string-based expressions. A majority of UOMs only require a single number to be used as a conversion factor. Currently, a formula is auto-generated for them and evaluated for each UOM conversion. Instead, a majority of UOMs can calculate conversions using a single number.

# Tasks
- [x] Introduce new enum `TUOMType` to attach to each `TUOM` object.
- [x] Introduce necessary properties in `TUOM` object.
- [x] Introduce `Owner` on `TUOM`, intended for auto-registered Metric UOMs.
  - All "child" UOMs will be assigned the "base" as their "owner" / "parent".
  - This is because in the event of "unregistering" such a UOM, it needs to unregister ALL related ones too.
- [x] Modify conversion routines to respect new properties.
- [x] Update all UOMs to register with new method as necessary.
